name: bst270-police-settlements
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.4.2
  - r-tinytex=0.54
  - r-scales=1.3.0
  - r-here=1.0.1
  - r-this.path=2.6.0
  - r-tidylog=1.1.0
  - r-plyr=1.8.9
  - r-lubridate=1.9.4
  - r-forcats=1.0.0
  - r-dplyr=1.1.4
  - r-purrr=1.0.2
  - r-readr=2.1.5
  - r-tibble=3.2.1
  - r-tidyverse=2.0.0
  - r-readxl=1.4.3
  - r-stringr=1.5.1
  - r-tidyr=1.3.1
  - r-ggplot2=3.5.1
  - r-sass=0.4.9
  - r-generics=0.1.3
  - r-renv=1.0.11
  - r-stringi=1.8.4
  - r-hms=1.1.3
  - r-digest=0.6.37
  - r-magrittr=2.0.3
  - r-evaluate=1.0.3
  - r-grid
  - r-timechange=0.3.0
  - r-fastmap=1.2.0
  - r-cellranger=1.1.0
  - r-rprojroot=2.0.4
  - r-jsonlite=1.8.9
  - r-jquerylib=0.1.4
  - r-cli=3.6.3
  - r-rlang=1.1.5
  - r-munsell=0.5.1
  - r-withr=3.0.2
  - r-cachem=1.1.0
  - r-yaml=2.3.10
  - r-tools
  - r-tzdb=0.4.0
  - r-colorspace=2.1-1
  - r-vctrs=0.6.5
  - r-r6=2.5.1
  - r-lifecycle=1.0.4
  - r-clisymbols=1.2.0
  - r-pkgconfig=2.0.3
  - r-pillar=1.10.1
  - r-bslib=0.8.0
  - r-gtable=0.3.6
  - r-glue=1.8.0
  - r-rcpp=1.0.14
  - r-xfun=0.50
  - r-tidyselect=1.2.1
  - r-rstudioapi=0.17.1
  - r-knitr=1.49
  - r-htmltools=0.5.8.1
  - r-rmarkdown=2.29
  - r-compiler

